### PR TITLE
Upgrade to Bevy 0.6

### PR DESCRIPTION
**Pull request by SUPERCILEX**

### CODE REVIEW

**Comment by jomala** [comment]
@SUPERCILEX - This all looks good. (It's basically a complete rewrite, but it looks like a good one!). I'll try to find time tonight to run it.

Assuming I see no issues, are you happy for it to be merged and tagged, or are you still making changes?

**Comment by jomala** [comment]
The README needs an update to the code snippet and to mention about the font requirement (which is the one part of the API I'm not sure about) but I can do that.

**Comment by SUPERCILEX** [comment]
Oh lol, was just working on a response. Will update docs and readme.

**Comment by jomala** [comment]
This is now merged with some README changes.

**Comment by jomala** [comment]
Sorry - wasn't sure whether we'd manage a conversation!

**Comment by SUPERCILEX** [comment]
Awesome! :) I'll take a look at docs then.

**Comment by jomala** [comment]
I think the README is okay now. Say if you think it should be updated.

I've not tagged yet.

**Comment by SUPERCILEX** [comment]
Originally planned reply since I had started it anyway lol.

---

Whoops, forgot I'd opened this PR on master — didn't mean for it to become a dumping ground for all my changes. :)

The key improvements are:
- Fully removing all UI when disabled (used to be set to blank)
- Minimizing work done when disabled (just a few if checks)
  - That said, I wish there was a way to remove the system entirely, but then I don't know how to re-add the system if we get enabled again. Maybe once the states rewrite happens it'll be possible to put our systems in a state and have users easily add/remove our state as an overlay. (Right now states are just a stack which makes composition difficult.)
  - There's also the issue of the frame timings still being collected, but I filed an issue for that: https://github.com/bevyengine/bevy/issues/3767
- Relying primarily on Bevy APIs instead of custom configuration

Regarding the fonts and camera, I got that advice from here: https://github.com/bevyengine/bevy/discussions/3770. Basically both font solutions are bad and not having a camera is bad dev UX, but both of those issues are planned to be fixed.

**Comment by jomala** [comment]
Looks like I've never tagged this or pushed to crates.io. Not sure it's worth it without a bit more functionality. Say if you disagree.

Do feel free to provide more updates as PRs. I don't find much time for Bevy, but I do try to maintain my crates.

**Comment by SUPERCILEX** [comment]
> Looks like I've never tagged this or pushed to crates.io.

Pretty sure you did, still looking for it.

**Comment by SUPERCILEX** [comment]
Here it is: https://crates.io/crates/bevy_screen_diags

**Pull request merged**
